# Generated by Django 5.0.6 on 2024-10-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destacada', models.BooleanField(default=False)),
            ],
        ),
    ]
