# Generated by Django 5.0.6 on 2024-10-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsulas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsula',
            name='subtitulo',
        ),
    ]
