# Generated by Django 5.0.6 on 2024-10-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsulas', '0002_remove_capsula_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsula',
            name='url',
        ),
        migrations.AddField(
            model_name='capsula',
            name='archivo',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
