# Generated by Django 5.0.6 on 2024-10-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsulas', '0004_alter_capsula_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsula',
            name='titulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
