# Generated by Django 5.0.6 on 2024-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/productos')),
            ],
        ),
        migrations.CreateModel(
            name='Emprendedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('informacion', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('foto', models.ImageField(upload_to='imagenes/emprendedoras')),
                ('telefono', models.CharField(max_length=50)),
                ('productos', models.ManyToManyField(to='emprendedoras.producto')),
            ],
        ),
    ]
