# Generated by Django 5.0.6 on 2024-10-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_destacada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to='archivos/noticias/imagenes'),
        ),
    ]
