# Generated by Django 5.0.6 on 2024-10-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarruselInicioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField()),
                ('imagen', models.ImageField(upload_to='archivos/imagenes')),
                ('url_redirect', models.URLField(null=True)),
            ],
        ),
    ]
