# Generated by Django 5.0.6 on 2024-10-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carruselinicioimagen',
            name='posicion',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
