# Generated by Django 5.0.6 on 2024-10-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='correo_electronico',
        ),
    ]
